# Generated by Django 4.2.5 on 2024-01-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='key',
            field=models.CharField(max_length=50),
        ),
    ]
