# Generated by Django 4.2.5 on 2024-04-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userotp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='attempts',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useraccount',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
