# Generated by Django 4.2.5 on 2024-04-18 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_useraccount_attempts_useraccount_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='attempts',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
