# Generated by Django 4.2.5 on 2023-12-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, related_name='VendorProjects', to='system.project'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='VendorUsers', to='account.useraccount'),
        ),
    ]
