# Generated by Django 4.2.5 on 2023-12-30 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_alter_vendor_projects_alter_vendor_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('delivery_date', models.DateField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_deadline', models.DateTimeField()),
                ('Quote_must_be_valid_until', models.DateField()),
                ('status', models.CharField(choices=[('s', 'Sent'), ('v', 'Viewed'), ('r', 'Replyed')], default='p', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('RFQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RFQfiles', to='system.rfq')),
            ],
        ),
        migrations.AddField(
            model_name='rfq',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rfqcurrency'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='products',
            field=models.ManyToManyField(related_name='RFQProduct', to='system.product'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.project'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rfqtype'),
        ),
        migrations.AddField(
            model_name='rfq',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.productuom'),
        ),
    ]
