# Generated by Django 4.2.5 on 2024-01-02 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_alter_productcategory_name_alter_productuom_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='Bidder_can_add_items',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='Bidder_can_change_quantity',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='Bidder_can_change_submitted_quote',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='Quotes_required_for_all_items',
            field=models.CharField(choices=[('y', 'Yes'), ('n', 'No')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='RFQ_ID',
            field=models.CharField(default=571, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='bidder_id',
            field=models.CharField(default=20000001, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfq',
            name='ship_to_address',
            field=models.TextField(default='GTS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
