# Generated by Django 4.2.5 on 2024-01-08 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('system', '0005_product_item_rfq_bidder_can_add_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('net_value', models.PositiveBigIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('RFQ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rfq')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rfqcurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.AlterField(
            model_name='filehandler',
            name='file',
            field=models.FileField(upload_to='files/Invoices/'),
        ),
        migrations.AlterField(
            model_name='rfqfilehandler',
            name='file',
            field=models.FileField(upload_to='files/RFQ/'),
        ),
        migrations.CreateModel(
            name='QuotationFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/Quotation/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quotationfiles', to='system.quotation')),
            ],
        ),
    ]
