# Generated by Django 4.2.5 on 2024-01-08 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_quotation_alter_filehandler_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('a', 'Approved'), ('r', 'Rejected')], default='c', max_length=256),
        ),
    ]
