# Generated by Django 4.2.5 on 2024-01-11 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('system', '0009_quotation_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='feedback',
        ),
        migrations.CreateModel(
            name='RejectedQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='Quotation Rejected')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovedQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField(default='Quotation Approved')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.quotation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
            ],
        ),
    ]
