# Generated by Django 4.2.5 on 2024-01-15 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userotp_key'),
        ('system', '0010_remove_quotation_feedback_rejectedquotation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='POMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precentage', models.PositiveBigIntegerField()),
                ('due', models.PositiveBigIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=256)),
                ('total_value', models.PositiveBigIntegerField()),
                ('shipping_terms', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.useraccount')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.rfqcurrency')),
                ('milestones', models.ManyToManyField(related_name='POMilestones', to='system.pomilestone')),
            ],
        ),
        migrations.CreateModel(
            name='POFileHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/PO/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='POfiles', to='system.purchaseorder')),
            ],
        ),
    ]
