# Generated by Django 4.2.5 on 2024-01-16 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_pomilestone_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='Quotation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='system.quotation'),
            preserve_default=False,
        ),
    ]
