# Generated by Django 4.2.5 on 2024-01-16 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_purchaseorder_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='Quotation',
            new_name='quotation',
        ),
    ]
