# Generated by Django 4.2.5 on 2024-01-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_rename_quotation_purchaseorder_quotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='total_value',
            field=models.FloatField(),
        ),
    ]
