# Generated by Django 4.2.5 on 2024-01-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alter_purchaseorder_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomilestone',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
