# Generated by Django 4.2.5 on 2024-01-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_alter_pomilestone_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomilestone',
            name='due',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
