# Generated by Django 4.2.5 on 2024-01-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_alter_invoice_milestone_alter_invoice_po_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='project_name',
            new_name='project',
        ),
    ]
