# Generated by Django 4.2.5 on 2024-01-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_rename_project_name_invoice_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomilestone',
            name='remaining',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
