# Generated by Django 4.2.5 on 2024-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_pomilestone_remaining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(),
        ),
    ]
